first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('', views.index,name='index'),
    path('other', views.other,name='other'),
    path('relative', views.relative,name='relative'),
    path('base', views.base,name='base'),
    path('register', views.register,name='register'),
    path('user_login', views.user_login,name='user_login')
]

my_first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from first_app import views

urlpatterns = [
    path('', views.index,name='index'),
    path('logout', views.user_logout,name='logout'),
    #path('formpage', views.form_name_view,name='form_name'),
    #path('formpage', views.form_name_view,name='form_name'),
    path('', include('first_app.urls')),
    path('admin/', admin.site.urls),
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

#Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length = 246, unique = True)
    
    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length = 246, unique = True)
    url = models.URLField(unique = True)

    def __str__(self):
        return self.name
class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')
		

#custom validation
# def check_for_z(value):
# 	if value[0].lower() != 'z':
# 		raise forms.ValidationError("Name must start with z")



#class FormName(forms.Form):

	#custom validation
	# name = forms.CharField(validator=[check_for_z])

	# name = forms.CharField()
	# email = forms.CharField()
	# verify_email = forms.EmailField(label='Enter your email again!')
	# text = forms.CharField(widget= forms.Textarea)
	# botcatcher = forms.CharField(required = False,
	# 							 widget = forms.HiddenInput,
	# 							 validators = [validators.MaxLengthValidator(0)])

	#email matching
	# def clean(self):
	# 	all_clean_data = super().clean()
	# 	email = all_clean_data['email']
	# 	vmail = all_clean_data['verify_email']

	# 	if email != vmail:
	# 		raise forms.ValidationError('Make sure email match!')



	#botcatcher validation
	# def clean_botcatcher(self):
	# 	botcatcher = self.cleaned_data['botcatcher']
	# 	if len(botcatcher)>0:
	# 		raise forms.ValidationError("Got a Bot!")
	# 	return botcatcher

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import AccessRecord,Topic,Webpage
from first_app.forms import UserForm,UserProfileInfoForm
from first_app import forms


from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    # my_dict = {'insert_me':"Hello I am from views.py!"}
    # return render(request,'first_app/index.html',context=my_dict)

    # webpage_list = AccessRecord.objects.order_by('date')
    # date_dict = {'access_records':webpage_list}
    # return render(request,'first_app/index.html',context=date_dict)

    return render(request,'first_app/index.html')

def base(request):

    return render(request,'first_app/base.html')

# def form_name_view(request):

# 	form = forms.FormName()

# 	if request.method == 'POST':
# 		form = forms.FormName(request.POST)

# 		if form.is_valid():
# 			print('Validation Successful')
# 			print('Name: '+form.cleaned_data['name'])
# 			print('Email: '+form.cleaned_data['email'])
# 			print('Text: '+form.cleaned_data['text'])


# 	return render(request,'first_app/form_page.html',{ 'form':form })

def other(request):
	return render(request, 'first_app/other.html')

def relative(request):
	return render(request, 'first_app/relative_url_templates.html')

@login_required
def spacial(request):
    return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponse(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()

            registered = True
        else:
                print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_app/register.html', {'user_form':user_form,
                                                                'profile_form':profile_form,
                                                                'register':registered})




def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username='username',password='password')

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not account')
        else:
            print('username:{} and password:{}'.format(username,password))
            return HttpResponse('Invalid login details')
    else:
        return render(request,'first_app/login.html',{})

templates/first_app/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Base_page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
				<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
				<li><a class="navbar-link" href="{% url 'first_app:register' %}">Register</a></li>
			</ul>
		</div>
	</nav>
	<div class="container">
		{% block body_block %}

		{% endblock %}
	</div>

</body>
</html>

templates/first_app/form_page.html
<!DOCTYPE html>
<html>
<head>
	<title>form</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<h2>Fill out the form</h2>
		<form method="post">
			{{form.as_p}}
			{% csrf_token %}
			<input type="submit" class="btn btn-primary" value="submit">
		</form>
	</div>
</body>
</html>

templates/first_app/index.html
<!-- <!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My first app</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
</head>
<body> -->
        <!-- {{ insert_me }}
    <h1>Hello this is index html</h1>
    
    <img src="{% static "images/image.png" %}" alt="image"> -->

<!--     <h1>Hy! Welcome to django level two!</h1>
    <h2>Here are the access records:</h2>
        <div class="django">
            {% if access_records %}
                <table>
                    <thead>
                        <th>Site Name</th>
                        <th>Date Access</th>
                    </thead>
                    <tbody>
                        {% for acc in access_records %}
                        <tr>
                            <td>{{ acc.name }}</td>
                            <td>{{ acc.date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
       -->          <!-- {% else %}
                <p>No Access records found</p>
                {% endif %} -->
<!--         </div>
 -->
<!-- </body>
</html> -->



        <div class="jumbotron">
            <h1>This our first form page</h1>
            <h3>This is the front page</h3>
        </div>
        {% if user.is_authenticated %}
        <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">Login</a></li>
        {% endif %}

templates/first_app/login.html
{% extends "first_app/base.html" %}
{% load staticfiles %}


{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'first_app:user_login' %}" method ="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" name="" value="Login">
    </form>
</div>


{% endblock %}

templates/first_app/other.html
<!DOCTYPE html>
<html>
<head>
	<title>Other_page</title>
</head>
<body>
	<h1>Other page</h1>
</body>
</html>

templates/first_app/register.html
{% extends "first_app/base.html" %}
{% load staticfiles %}


{% block body_block %}

<div class="jumbotron">
    {% if register%}
    <h1>Thank you for Register</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the form</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>

    {% endif %}
</div>



{% endblock %}

templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
	<title>Relative_url</title>
</head>
<body>
	<h1>Welcome! to relative url</h1>
	<a href="{% url 'first_app:other' %}">Go to the other page</a><br/>
	<a href="{% url 'admin:index' %}">Go to the admin page</a><br/>
	<a href="{% url 'index' %}">Go to the index page</a>
</body>
</html>

templates/first_app/users.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Users</title>
</head>
<body>
	<h1>Here are the users</h1>

	{% if users%}

		<ol>
			{% for person in users %}

				<li>Users info</li>
				<ul>
					<li>First Name: {{ person.first_name }}</li>
					<li>Last Name: {{ person.last_name }}</li>
					<li>Email: {{ person.email }}</li>
				</ul>

			{% endfor %}
			
		</ol>

	{% endif %}
</body>
</html>